# Build in Github Action

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'qemu.config/qemu.config'
  pull_request:
    branches: [ main ]
    paths:
      - 'qemu.config/qemu.config'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone buildroot
        run: git clone git://git.buildroot.org/buildroot
      - name: Clone this repo
        run: git clone https://raspiduino:${{ secrets.MY_ACCESS_TOKEN }}@github.com/raspiduino/.config
      - name: Copy file from this repo to buildroot
        run: cp .config/qemu.config/qemu.config buildroot/.config
      - name: Build
        run: |
          cd buildroot
          make oldconfig
          make -j2
      - name: Rename the ISO file
        run: |
          cd buildroot/output/images
          mv rootfs.iso9660 QEMU-buildroot.iso
      - name: Pre-release the ISO
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Pre-release ISO"
          files: buildroot/output/images/QEMU-buildroot.iso
